---
version: "3"

services:
    redis-db:
        image: redis:7 
        ports:
            - 6379:6379
        volumes:
            - ./data:/data 
        user: "1000:1000"
        command: ["--save", "1", "1"]
    flask-app:
        build:
            context: ./ 
            dockerfile: ./Dockerfile
        depends_on:
            - redis-db
        image: rguarneros065/flask-worldpop_api:1.0 
        # ports:
        #     - 5000:5000
        command: ["python", "api.py"] # AI used to run the api 
        environment: # AI used to add environment 
        # - REDIS_HOST=redis-db
        - REDIS_HOST=127.0.0.1
        - LOG_LEVEL=DEBUG # change to WARNING after 
        network_mode: host
    worker: 
        build: 
            context: ./ 
            dockerfile: ./Dockerfile
        depends_on: 
            - redis-db
        image: rguarneros065/flask-worldpop_api:1.0 
        command: ["python", "worker.py"]
        environment: 
        # - REDIS_HOST=redis-db
        - REDIS_HOST=127.0.0.1
        - LOG_LEVEL=DEBUG # change to WARNING after 
    