---
version: "3"

services:
    redis-db:
        image: redis:7 
        ports:
            - 6379:6379
        volumes:
            - ./data:/data 
        user: "1000:1000"
        command: ["--save", "1", "1"]
    flask-app:
        build:
            context: ./ 
            dockerfile: ./Dockerfile
        depends_on:
            - redis-db
        image: rguarneros065/flask-redis-gene_api:1.0 
        ports:
            - 5000:5000
        command: [api.py] # AI used to run the api 
        environment: # AI used to add environment 
        - REDIS_HOST=redis-db
        - LOG_LEVEL=WARNING
    worker: 
        build: 
            context: ./ 
            dockerfile: ./Dockerfile
        depends_on: 
            - redis-db
        image: rguarneros065/flask-redis-gene_api:1.0   
        command: [worker.py] 
        environment: 
        - REDIS_HOST=redis-db
        - LOG_LEVEL=WARNING
    